name: Auto Merge Version Bump

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - master

jobs:
  auto-merge:
    if: github.event.pull_request.head.ref == 'version-bump'
    runs-on: ubuntu-latest

    steps:
      - name: Auto merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin --delete-branch