name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # trigger only on tags like v1.0.0, v1.0.0-rc, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history so git branch check works

      - name: Verify tag commit is on master branch
        run: |
          TAG_COMMIT_SHA=${GITHUB_SHA}
          echo "Tag commit SHA: $TAG_COMMIT_SHA"
          if git branch --contains "$TAG_COMMIT_SHA" | grep -q 'master'; then
            echo "✅ Tag commit is on master branch."
          else
            echo "⚠️ Tag commit is NOT on master branch. Exiting early."
            exit 78  # 78 = neutral exit, marks job as skipped in some runners
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore --no-cache

      - name: Build project (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Extract version from tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${VERSION#v}"
          echo "Detected version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack NuGet package
        working-directory: src/EFCore.CrudKit.Library
        run: |
          echo "Packing EFCore.DataForge version: $VERSION"
          dotnet pack EFCore.CrudKit.Library.csproj \
            --no-build \
            -p:Configuration=Release \
            -p:PackageId=EFCore.DataForge \
            -p:Version="$VERSION" \
            -o out

      - name: Publish to NuGet
        if: success()
        working-directory: src/EFCore.CrudKit.Library
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Publishing package(s) in src/EFCore.CrudKit.Library/out/ ..."
          dotnet nuget push out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate