name: CI & Release

on:
  push:
    branches:
      - master

permissions:
  contents: write    # needed to push commits and tags
  packages: write    # for pushing to NuGet

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push commits/tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore --no-cache

      - name: Get current version from csproj
        id: get_version
        run: |
          VERSION=$(xmllint --xpath "string(//Version)" src/EFCore.CrudKit.Library/EFCore.CrudKit.Library.csproj)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump version with prerelease support
        id: bump_version
        run: |
          FULL_VERSION="$VERSION"

          CORE_VERSION="${FULL_VERSION%%-*}"
          PRERELEASE="${FULL_VERSION#"$CORE_VERSION"}"
          PRERELEASE="${PRERELEASE#-}"

          IFS='.' read -r MAJOR MINOR PATCH <<<"$CORE_VERSION"

          if [ -z "$PRERELEASE" ] || [ "$PRERELEASE" = "$FULL_VERSION" ]; then
            PATCH=$((PATCH + 1))
            if [ "$PATCH" -gt 9 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
            fi
            if [ "$MINOR" -gt 9 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          else
            PR_LABEL="${PRERELEASE%%.*}"
            PR_NUM="${PRERELEASE#"$PR_LABEL."}"

            if ! [[ "$PR_NUM" =~ ^[0-9]+$ ]]; then
              PR_NUM=1
            else
              PR_NUM=$((PR_NUM + 1))
            fi

            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}-$PR_LABEL.$PR_NUM"
          fi

          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update csproj with new version
        run: |
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" src/EFCore.CrudKit.Library/EFCore.CrudKit.Library.csproj

      - name: Commit version bump and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/EFCore.CrudKit.Library/EFCore.CrudKit.Library.csproj
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git push origin master

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"

      - name: Build project (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        working-directory: src/EFCore.CrudKit.Library
        run: |
          dotnet pack EFCore.CrudKit.Library.csproj \
            --no-build \
            -p:Configuration=Release \
            -p:PackageId=EFCore.DataForge \
            -p:Version="$NEW_VERSION" \
            -o out

      - name: Publish to NuGet
        working-directory: src/EFCore.CrudKit.Library
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate