name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project (Release)
        run: dotnet build --configuration Release

      - name: Set package version from tag
        # GITHUB_REF is like "refs/tags/v1.2.3"
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG#v}
          echo "Detected tag: $TAG"
          echo "VERSION=$TAG" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: |
          echo "Packing EFCore.DataForge version: $VERSION"
          cd src/EFCore.CrudKit.Library
          dotnet pack EFCore.CrudKit.Library.csproj \
            --no-build \
            -p:Configuration=Release \
            -p:PackageId=EFCore.DataForge \
            -p:Version="$VERSION" \
            -o out

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Publishing package(s) in out/ ..."
          dotnet nuget push "out/*.nupkg" \
            --api-key "$NUGET_API_KEY" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate